### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [5265250, 21061]

### ISSUE THREAD

**Issue by dzhen19** [ardkastrati/EEGEyeNet#1]
Hey! We're trying to run the benchmark. When running `main.py`, we're getting a dimensionality error. Here's our full error log: 

```
LinearSVC(C=0.01, max_iter=1200, tol=1e-05)
Traceback (most recent call last):
  File "/Users/derrickzhen/code/cs91/EEGEyeNet/main.py", line 63, in <module>
    main()
  File "/Users/derrickzhen/code/cs91/EEGEyeNet/main.py", line 54, in main
    benchmark(trainX, trainY)
  File "/Users/derrickzhen/code/cs91/EEGEyeNet/benchmark.py", line 105, in benchmark
    try_models(trainX=trainX, trainY=y, ids=ids, models=models, scoring=scoring)
  File "/Users/derrickzhen/code/cs91/EEGEyeNet/benchmark.py", line 68, in try_models
    trainer.fit(X_train, y_train, X_val, y_val)
  File "/Users/derrickzhen/code/cs91/EEGEyeNet/StandardML_Models/StandardClassifier_1D.py", line 42, in fit
    self.model.fit(trainX, trainY.ravel())
  File "/opt/homebrew/lib/python3.9/site-packages/sklearn/svm/_classes.py", line 246, in fit
    X, y = self._validate_data(
  File "/opt/homebrew/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/validation.py", line 981, in check_X_y
    check_consistent_length(X, y)
  File "/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/validation.py", line 332, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [5265250, 21061]
```

Looks like this has to do with the reshaping of the EEG data for model fitting? 
In Line 40 of `StandardClassifier_1D.py`, the data is reshaped with the following method: 
`trainX = trainX.reshape((-1, 258))  # TODO: A hack for now`

Then, when this reshaped data is plugged into the model for fitting / inference, the error is thrown. Is this WAI? How can we repro your results? 

Thank you!

**Comment by MartynaPlomecka** [comment]
XDDDD
Hack for now

**Comment by ardkastrati** [comment]
Can you give a context which data exactly is being loaded? Maybe share the logging data, before the error? It seems like your X shape is 250 times bigger than Y shape.

**Comment by dzhen19** [comment]
Hey, I'm using the `LR_task_with_antisaccade_synchronised_max.npz`, downloaded from [here](https://osf.io/v8u7h/). 

Here are the logs I'm getting when I run `main.py` before the error: 
2022-02-24 16:12:58,144 [INFO] Started the Logging
2022-02-24 16:12:58,144 [INFO] Using pytorch
2022-02-24 16:12:58,144 [INFO] Loading LR_task_with_antisaccade_synchronised_max.npz
2022-02-24 16:13:18,357 [INFO] X training loaded.
2022-02-24 16:13:18,543 [INFO] (30825, 500, 129)
2022-02-24 16:13:18,819 [INFO] y training loaded.
2022-02-24 16:13:18,968 [INFO] (30825, 2)
2022-02-24 16:13:19,365 [INFO] Training the models
2022-02-24 16:14:39,385 [INFO] Training of KNN
2022-02-24 16:14:39,834 [INFO] <StandardML_Models.StandardClassifier_1D.StandardClassifier_1D object at 0x1576d8130>
KNeighborsClassifier(leaf_size=10, n_jobs=-1, n_neighbors=100)

**Comment by ardkastrati** [comment]
I see, for the standard machine learning models we use in our benchmark only the prepared data with hilbert transformations. That is the data that should be used for standard classifier should be « …_hilbert.npz ». Check config.py and make sure the feature extraction is set to true, and the build_file_name() function in config.py uses the hilbert transformed data. This should make possible to reproduce our results.

Using data with shape (500,129) for standard classifiers does not scale well, and some of the models might take very long until they terminate. As a general comment I will think whether to make possible to use any type of data, or simply not allow to use unprepared data. In any case, let me know whether using hilbert transformed data helped. The data can be found in the same folder, with the only difference that they have _hilbert.npz in their name.

**Comment by dzhen19** [comment]
I'm able to repro the benchmarks with the hilbert tansformed data. Thank you!

**Comment by binaryguy1001101** [comment]
Is there any way to turn the hilbert-transformed data into covariance matrices, or does that only work with the regular data?
